# Generated by Django 5.2.15 on 2026-07-05 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okrug', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('population', models.CharField(blank=True, max_length=255)),
                ('capacity', models.CharField(blank=True, max_length=255)),
                ('address_raw', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ('okrug', 'district'),
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255)),
                ('okrug', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=512)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('capacity', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelters', to='shelters.district')),
            ],
            options={
                'verbose_name': 'shelter',
                'verbose_name_plural': 'shelters',
                'ordering': ('okrug', 'district_name', 'address'),
            },
        ),
    ]
