# Generated by Django 5.2.15 on 2026-07-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivilDefenseBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('city', 'city'), ('region', 'region'), ('district', 'district')], db_index=True, max_length=16)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('federal_district', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('body_name', models.TextField(blank=True)),
                ('org_name', models.TextField(blank=True)),
                ('body_type', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=512)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('source_url', models.CharField(blank=True, max_length=512)),
                ('notes', models.TextField(blank=True)),
                ('custom_instructions', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'civil defense body',
                'verbose_name_plural': 'civil defense bodies',
                'ordering': ('level', 'region', 'city', 'district'),
            },
        ),
    ]
